In [1]:
import numpy as np
# Definisikan suatu matriks A berordo 2x3 dengan entri-entri yang ditentukan sendiri
#tulis code disini
A = [[2, 1, 2],
    [3, 5, 6]]
print ('matriks A \n',A)

# Definisikan suatu matriks B berordo 3x3 dengan entri-entri yang ditentukan sendiri
#tulis code disini
B = [[7, 8, 5],
    [4, 7, 2],
    [1, 9, 6]]
print ('matriks B \n', B)

# Definisikan suatu matriks C berordo 3x2 dengan entri-entri yang ditentukan sendiri
#tulis code disini
C = [[2, 4],
    [3, 7],
    [4, 8]]
print ('matriks C \n',C)
print ('\n')

# Carilah perkalian matriks A dan B kemudian print hasilnya
#tulis code disini
print ('matriks A X B \n', np.matmul(A,B))

# Carilah perkalian matriks B dan C kemudian print hasilnya
#tulis code disini
print ('matriks B X C \n', np.matmul(B,C))

# Carilah perkalian matriks C dan A kemudian print hasilnya
#tulis code disini
print ('matriks C X A \n', np.matmul(C,A))

matriks A 
 [[2, 1, 2], [3, 5, 6]]
matriks B 
 [[7, 8, 5], [4, 7, 2], [1, 9, 6]]
matriks C 
 [[2, 4], [3, 7], [4, 8]]


matriks A X B 
 [[ 20  41  24]
 [ 47 113  61]]
matriks B X C 
 [[ 58 124]
 [ 37  81]
 [ 53 115]]
matriks C X A 
 [[16 22 28]
 [27 38 48]
 [32 44 56]]
